version: "3"
services:
  alice:
    build:
      context: ./alice
      dockerfile: ../Dockerfile
    container_name: alice
    ports:
      - "5001:5000"
    depends_on:
      - bob
    networks:
      - chatnet
    env_file:
      - ./alice/.env

  bob:
    build:
      context: ./bob
      dockerfile: ../Dockerfile
    container_name: bob
    ports:
      - "5002:5000"
    networks:
      - chatnet
    env_file:
      - ./bob/.env

networks:
  chatnet:
    driver: bridge
